name: Build rk3566-tspi.img

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  ARCH: arm64


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          # 关键：保留文件权限
          persist-credentials: false

      - name: Fix Script Permissions
        run: |
          find . -type f -name "*.sh" -exec chmod +x {} \;
          find . -type f -name "mkimg" -exec chmod +x {} \;
          find . -type f -name "resource_tool" -exec chmod +x {} \;
          find . -type f -name "mkbootimg" -exec chmod +x {} \;
          chmod +x ./scripts/*
          
      

      - name: Install Latest LZ4
        run: |
          # 从 GitHub 下载最新版 LZ4
          LZ4_LATEST=$(curl -s https://api.github.com/repos/lz4/lz4/releases/latest | grep 'tarball_url' | cut -d\" -f4)
          wget $LZ4_LATEST -O lz4-latest.tar.gz
          tar -xzf lz4-latest.tar.gz
          cd lz4-lz4-*
          make -j$(nproc)
          sudo make install
          sudo ldconfig
          lz4 --version

          
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            device-tree-compiler \
            u-boot-tools \
            libssl-dev \
            bc \
            flex \
            bison \
            libncurses-dev
          sudo -E apt-get -y install $(curl -fsSL https://tinyurl.com/ubuntu2204-build-armbian)

      - name: Setup ARM Toolchain
        run: |
          wget https://developer.arm.com/-/media/Files/downloads/gnu/14.2.rel1/binrel/arm-gnu-toolchain-14.2.rel1-x86_64-aarch64-none-linux-gnu.tar.xz
          tar xf arm-gnu-toolchain-14.2.rel1-x86_64-aarch64-none-linux-gnu.tar.xz
          echo "$(pwd)/arm-gnu-toolchain-14.2.rel1-x86_64-aarch64-none-linux-gnu/bin" >> $GITHUB_PATH



      - name: Build Kernel
        run: |   
          echo "$(pwd)"
          # 获取内核版本号
          echo "kernel_main_version=$(make kernelversion)" >> $GITHUB_ENV
          make ARCH=$ARCH CROSS_COMPILE=aarch64-none-linux-gnu-  olddefconfig
          make ARCH=$ARCH CROSS_COMPILE=aarch64-none-linux-gnu-  rk3566-lckfb-tspi.img  -j$(nproc)

          make ARCH=$ARCH CROSS_COMPILE=aarch64-none-linux-gnu-  modules_install  INSTALL_MOD_PATH=./modules
          echo  "查看编译好的boot.img"
          ls -l boot.img
          echo "重命名boot.img为rk3566-lckfb-tspi-boot-${{ env.kernel_main_version }}.img"
          mv boot.img  rk3566-lckfb-tspi-boot-${{ env.kernel_main_version }}.img
          ls  -l rk3566-lckfb-tspi-boot-${{ env.kernel_main_version }}.img          
          echo "当前所在编译路径：$(pwd)"
          # 打包模块
          cd  /home/runner/work/linux/linux/modules/lib/modules
          echo "进入modules路径：$(pwd)"

          echo  "查看modules"
          ls -l
          ls -l ${{ env.kernel_main_version }}
          echo "打包modules"
          tar -zcvf ${{ env.kernel_main_version }}-modules.tar.gz   ${{ env.kernel_main_version }}
          echo "查看打包的modules.tar.gz"
          ls  -l
     
      
      - name: Build Kernel-headers
        run: |
          # 制作linux-headers头文件
          mkdir  linux-headers-${{ env.kernel_main_version }}
          cp -a  Module.symvers      linux-headers-${{ env.kernel_main_version }}/
          cp -a  Makefile           linux-headers-${{ env.kernel_main_version }}/
          cp -a  scripts            linux-headers-${{ env.kernel_main_version }}/
          mkdir -p           linux-headers-${{ env.kernel_main_version }}/arch/arm64
          cp -a arch/arm64/include    linux-headers-${{ env.kernel_main_version }}/arch/arm64/include
          cp -a arch/arm64/kvm          linux-headers-${{ env.kernel_main_version }}/arch/arm64/kvm 
          cp -a arch/arm64/Makefile      linux-headers-${{ env.kernel_main_version }}/arch/arm64/Makefile
          cp -a include                  linux-headers-${{ env.kernel_main_version }}/
          cp -a .config                 linux-headers-${{ env.kernel_main_version }}/
          tar -zcvf  linux-headers-${{ env.kernel_main_version }}.tar.gz   linux-headers-${{ env.kernel_main_version }}
          echo "当前所在路径：$(pwd)"
          echo "查看打包的headers.tar.gz"
          ls  -l linux-headers-${{ env.kernel_main_version }}.tar.gz
      
      - name: Package Armbian Boot
        run: |
          mkdir -p  rk3566-lckfb-tspi-armbian-boot-${{ env.kernel_main_version }}
          cp -a System.map  rk3566-lckfb-tspi-armbian-boot-${{ env.kernel_main_version }}/
          cp -a .config  rk3566-lckfb-tspi-armbian-boot-${{ env.kernel_main_version }}/
          cp -a /home/runner/work/linux/linux/arch/arm64/boot/Image  rk3566-lckfb-tspi-armbian-boot-${{ env.kernel_main_version }}/vmlinuz
          cp -a /home/runner/work/linux/linux/arch/arm64/boot/dts/rockchip/rk3566-lckfb-tspi.dtb  rk3566-lckfb-tspi-armbian-boot-${{ env.kernel_main_version }}/
          mkinitramfs -o rk3566-lckfb-tspi-armbian-boot-${{ env.kernel_main_version }}/initrd.img   -k  ${{ env.kernel_main_version }} /home/runner/work/linux/linux/modules/lib/modules/${{ env.kernel_main_version }}
          mkimage -A arm64 -O linux -T ramdisk -C none -a 0 -e 0  -n "uInitrd ${{ env.kernel_main_version }}"  -d  rk3566-lckfb-tspi-armbian-boot-${{ env.kernel_main_version }}/initrd.img  rk3566-lckfb-tspi-armbian-boot-${{ env.kernel_main_version }}/uInitrd
          
          
          echo  "查看rk3566-lckfb-tspi-armbian-boot-${{ env.kernel_main_version }}下的文件"
          ls -l  rk3566-lckfb-tspi-armbian-boot-${{ env.kernel_main_version }}
          cd  rk3566-lckfb-tspi-armbian-boot-${{ env.kernel_main_version }}
          echo "打包rk3566-lckfb-tspi-armbian-boot-${{ env.kernel_main_version }}.tar.gz"
          tar -zcvf rk3566-lckfb-tspi-armbian-boot-${{ env.kernel_main_version }}.tar.gz  *
          mv  rk3566-lckfb-tspi-armbian-boot-${{ env.kernel_main_version }}.tar.gz  /home/runner/work/linux/linux/
          
          
      - name: Upload Kernel to Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name || format('v{0}', env.kernel_main_version) }}
          name: "Kernel ${{ env.kernel_main_version }}"
          
          artifacts: |
            /home/runner/work/linux/linux/rk3566-lckfb-tspi-boot-${{ env.kernel_main_version }}.img
            /home/runner/work/linux/linux/modules/lib/modules/${{ env.kernel_main_version }}-modules.tar.gz
            linux-headers-${{ env.kernel_main_version }}.tar.gz
            /home/runner/work/linux/linux/rk3566-lckfb-tspi-armbian-boot-${{ env.kernel_main_version }}.tar.gz
          body: "Auto-built  rk3566-lckfb-tspi-boot-${{ env.kernel_main_version }}"
          draft: false
          prerelease: false
